# Generated by Django 5.0.6 on 2024-06-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_size_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
